### ISSUE TITLE
help~~

### ISSUE THREAD

**Issue by stannnnnnnnn** [viennats/viennats-dev#30]
Which version of VTK does Viennats-dev require?
During the installation process when I go to the "make" step ,why is it displayed "Vtkobject.h: 56:44 error: extra '; ' and vtkAlogorithm.h;57;39;error: extra ';'"?

**Comment by XaverKlemenschits** [comment]
Hi,
I believe we used VKT 8.2.
However, note that development of viennats has staled and we suggest to use [ViennaLS](https://github.com/ViennaTools/ViennaLS) instead. It is a more flexible level set library which allows you to implement your own velocity fields and provides conversions into many useful file formats. Especially the python library of ViennaLS has shown to be extremely useful for developing process simulation models.
Best,
Xaver
