### ISSUE TITLE
I wanna perform Hole Etching with SF6_O2

### ISSUE THREAD

**Issue by TsuLab2023** [viennats/viennats-dev#32]
I use ViennaTS instead of ViennaPS because the code is easier to understand. However, I am having trouble finding any manuals or other information on etching with SF6_O2 plasma in the Examples. Please let me know how it is possible.

**Comment by FilipovicLado** [comment]
Dear colleague,

Thank you for your interest in ViennaTS and ViennaPS. Unfortunately ViennaPS is undergoing maintenance and we hope to have it up and running again in the next couple of days. In the meantime, ViennaTS is our legacy code which we no longer support. However, you should still be able to run the models which are implemented therein.

To install ViennaTS, run the following commands in your Linux terminal:
```
git clone https://github.com/viennats/viennats-dev.git
cd viennats-dev
mkdir build
cd build/
cmake ..
make
```

This will create the ViennaTS executable `viennats-2.3.2` inside the `build` folder.

You should then be able to run the 'SF6_Etching' example by opening terminal from the `/viennats-dev/examples/SF6_Etching/` folder and executing:

```
../../build/viennats-2.3.2 par3d.txt
```

You can modify the model to suit your needs by changing the parameters inside `par3d.txt`.

For information on the meaning behind the parameters and other information about ViennaTS, refer to the documentation in the `ViennaTS_User_Guide.pdf` file.

**Comment by TsuLab2023** [comment]
I used initial ViennaTS not viennats-dev.
I was able to use SF6O2Etching in ViennaTS by copy SF6O2Etching_dir in viennats-dev to ViennaTS.
Thank you.
