### ISSUE TITLE
Mask and hole shape settings

### ISSUE THREAD

**Issue by TsuLab2023** [viennats/viennats-dev#33]
I want to perform etching with SF6_O2 plasma with SiO2 set as mask. So I am trying to set up the SiO2 mask shape and the Si hole shape, but I am struggling because I don't know how to use dx and vtk files. How can I set up the initial shape of the mask?

**Comment by FilipovicLado** [comment]
Unfortunately, the ViennaTS tool requires you to generate the initial geometry outside of the ViennaTS tool. ViennaTS can then import the geometry (whether mask or wafer features) from several data formats (e.g., .dx, .vtk). To see how this is done, you can look through the SF6_CH2F2 example.
However, I would encourage you to switch to ViennaPS, which is working now. The process of installing it and running the SF6/O2 example may seem daunting, but it is actually quite straight forward. You can follow these steps.
- Open terminal inside the folder where you wish to download ViennaPS and run the following commands:
```
git clone https://github.com/ViennaTools/ViennaPS.git
cd ViennaPS
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=./install/
make buildDependencies
make install
```

- This will install all necessary ViennaPS header files to your `/build/install/` folder. 

- Now, open terminal in the example folder `ViennaPS/examples/holeEtching/` and modify the `CMakeLists.txt` file to look like this:

```
cmake_minimum_required(VERSION 3.4)

project("holeEtching")

set(ViennaPS_DIR "../../build/")
find_package(ViennaPS REQUIRED)

add_executable(${PROJECT_NAME} ${PROJECT_NAME}.cpp)
target_include_directories(${PROJECT_NAME} PUBLIC ${VIENNAPS_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${VIENNAPS_LIBRARIES})
configure_file(holeEtching.py ${CMAKE_CURRENT_BINARY_DIR}/holeEtching.py COPYONLY)
configure_file(config.txt ${CMAKE_CURRENT_BINARY_DIR}/config.txt COPYONLY)
```

- Now, from inside the `ViennaPS/examples/holeEtching` folder, run the following lines in terminal:

```
mkdir build && cd build
cmake ..
make
```

Inside the `build` folder, you will now have an executable `holeEtching` and a configuration file `config.txt`. The configuration file contains the domain, geometry, and model input parameters. Here, you will see that you can identify the radius of the hole you wish to etch, the mask thickness, and the taper angle of the mask. To run the configuration file, execute the following from inside the `build` folder:

```
./holeEtching config.txt
```

I hope this helps!

**Comment by TsuLab2023** [comment]
OK
Now, I am actually using both ViennaPS and ViennaTS.
I thought ViennaPS is difficult to understand how it worlks because of complex code, but it is easy to set desired parameters.
And, ViennaTS is easy to understand code, so it was helpful for my study.
Then I will try to understand ViennaPS.
